### ISSUE TITLE
some confused about the text  in the ui-slider-label-ticks chidren  span 

### ISSUE THREAD

**Issue by gaoguoxin** [bseth99/sandbox#3]
for some reason I have readed your code of the labeledslider ,and confused about the marker number
the fact my code is:

```
min:1, 
max: 12
tickLabels: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'] 
```

but it generate the marker default is 
'2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月,12
so if I want to generate
'1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'
I have to set

```
min:0, 
max: 11
```

accoridng to the code below, I think:   change  the code 
`labels[i*inr+min] ? labels[i*inr+min] : i*inr+min`
to  
`labels[i*inr] ? labels[i*inr] : i*inr`
  is that correct?
 bellow is the function of _drawLabels

```
for (;i<=cnt;i++) {
  $('<div>').addClass( 'ui-slider-label-ticks' )
  .css( dir, (Math.round( i / cnt * 10000 ) / 100) + '%' )
  .html( '<span>'+( labels[i*inr+min] ? labels[i*inr+min] : i*inr+min)+'</span>').appendTo( $lbl );
}
```

**Comment by bseth99** [comment]
I think the behavior was intentional.  Look at the demo http://bseth99.github.io/jquery-ui-extensions/tests/visual/labeledslider/options.html and check the "Show Labels" option and increase the "Min".  If the min=1, then the label starts at Tues, not Mon.  If I remove the +min, then it would not start at Tues and you'd have to rebuild the array each time to match the current behavior.  Of course, you could argue it the other way too but in my uses I prefer to have a stable set of labels and adjust the min/max to show a different range of labels on the slider.  Mon is always 0, Tue is always 1, so on.  In the example, I copied the label array several times to allow it to loop up to the maximum allowable range on the slider so it would repeat accordingly (because a missing label results in the index being drawn).

**Comment by gaoguoxin** [comment]
In any case, all good thank you

**Comment by bseth99** [comment]
The only other thing I can add is you're not required to use an array - you can also use a object hash indexed with numbers corresponding to the slider values.  That way min=1 can be mapped to the first object hash, etc.  

Check out http://bseth99.github.io/jquery-ui-extensions/tests/visual/labeledslider/variable_labels.html for an example of using a hash and creating different intervals of ticks/labels.
